@Scorpanion.API_HostAddress = http://localhost:5234

GET {{Scorpanion.API_HostAddress}}/weatherforecast/
Accept: application/json
###


POST {{Scorpanion.API_HostAddress}}/boardGame/create/
Accept: application/json
###
