services:
  postgres:
    environment:
      POSTGRES_PASSWORD: !reset null
      POSTGRES_PASSWORD_FILE: /run/secrets/scorpanion_db_password
    secrets:
      - scorpanion_db_password

  backend:
    environment:
      SCORPANION_DB_PASSWORD: !reset null
    secrets:
      - scorpanion_db_password

secrets:
  scorpanion_db_password:
    file: ${SCORPANION_DB_PASSWORD_FILE_PATH:?SCORPANION_DB_PASSWORD_FILE_PATH is required}
